apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-api
  labels:
    app: webhook-api
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: webhook-api
  template:
    metadata:
      labels:
        app: webhook-api
    spec:
      containers:
      - name: webhook-api
        image: visionir/webhook-api:live
        ports:
        - name: web
          containerPort:  8000
          protocol: TCP
      - name: webhook-api
        image: visionir/webhook-api:live
        ports:
        - name: web
          containerPort:  7750
          protocol: TCP
