services:
  smee:
    image: visionir/smee:client
    build:
      context: ./smee-client
      args:
        GH_OWNER: ${GH_OWNER}
        GH_REPO: ${GH_REPO}
        GH_TOKEN: ${GH_TOKEN}
        API_URL: ${API_URL}
        WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    ports:
      - "7750:7750"
    env_file:
      - .env

  api:
    image: visionir/webhook-api:live
    build:
      context: ./api
    volumes:
      - ./api/src:/app
      - ./api/data:/data
    ports:
      - "8000:8000"
    env_file:
      - .env
