name: build-tag-push
run-name: Build, Tag and Push new image for submodule
on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        type: string
        description: "Name of the image to build"
        required: true
    secrets:
      DOCKER_USER:
        description: "Docker Hub username"
        required: true
      DOCKER_TOKEN:
        description: "Docker Hub token"
        required: true
jobs:
  handle-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Validate workspace
        id: validate-workspace
        run: |
          echo $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          # sparse-checkout: .
          # path: .
          # set-safe-directory: false
      - name: Generate Date
        id: date
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        id: login-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Use Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          install: true
      - name: Valdiate path
        id: validate-path
        run: |
          echo $(pwd)
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{inputs.IMAGE_NAME}}:${{ steps.date.outputs.TAG_DATE }}.${{ github.run_number }}
