name: build-image-webhooks-api:api
run-name: Build new image for Webhooks API:api
on:
  push:
    paths:
      - "IaC/images/webhook-api/api/**"
    branches:
      - master
jobs:
  build-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        id: login-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Use Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          install: true
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./IaC/images/webhook-api/api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webhook-api:${{ steps.date.outputs.date }}:${{ github.run_number }}"
