name: build-image
run-name: Build new image
on:
  push:
    paths:
      - "IaC/images/webhook-api/api/src/**"
    branches:
      - master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Use Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          install: true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./IaC/images/webhook-api/api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webhook-api:

